/**
 * Centralized city lists for each featured country.
 *
 * These power:
 * - search country + city filters
 * - tutor profile country + city dropdowns
 * - city inference for free-text searches
 *
 * Important: Do not include "Online" here. "Online" is added by the callers.
 */
export const MARKET_CITIES_BY_COUNTRY_CODE: Record<string, string[]> = {
  // South Asia + MENA (kept in the same order as `TOP_COUNTRIES` for predictable sorting).
  PK: [
    "Karachi",
    "Lahore",
    "Islamabad",
    "Rawalpindi",
    "Faisalabad",
    "Multan",
    "Gujranwala",
    "Peshawar",
    "Quetta",
    "Sialkot",
    "Hyderabad",
    "Bahawalpur",
    "Abbottabad",
    "Sargodha",
    "Sukkur",
    "Larkana",
    "Sheikhupura",
    "Rahim Yar Khan",
    "Jhang",
    "Gujrat",
    "Mardan",
    "Mingora",
    "Nawabshah",
    "Mirpur Khas",
    "Kasur",
    "Dera Ghazi Khan",
    "Sahiwal",
    "Okara",
    "Wah Cantonment",
    "Dera Ismail Khan",
    "Chiniot",
    "Kamoke",
    "Hafizabad",
    "Sadiqabad",
    "Burewala",
    "Jacobabad",
    "Muzaffarabad",
    "Khushab",
    "Kohat",
    "Attock",
    "Khanewal",
    "Jhelum",
    "Nowshera",
    "Muzaffargarh",
    "Mandi Bahauddin",
    "Turbat",
    "Shikarpur",
    "Bahawalnagar",
    "Pakpattan",
    "Tando Adam",
  ],
  IN: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Surat",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Pimpri-Chinchwad",
    "Patna",
    "Vadodara",
    "Ghaziabad",
    "Ludhiana",
    "Agra",
    "Nashik",
    "Faridabad",
    "Meerut",
    "Rajkot",
    "Varanasi",
    "Srinagar",
    "Aurangabad",
    "Dhanbad",
    "Amritsar",
    "Allahabad",
    "Ranchi",
    "Howrah",
    "Coimbatore",
    "Jabalpur",
    "Gwalior",
    "Vijayawada",
    "Jodhpur",
    "Madurai",
    "Raipur",
    "Kota",
    "Chandigarh",
    "Guwahati",
    "Solapur",
    "Hubballi",
    "Tiruchirappalli",
    "Bareilly",
    "Mysuru",
  ],
  US: [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "Indianapolis",
    "San Francisco",
    "Seattle",
    "Denver",
    "Washington DC",
    "Nashville",
    "Oklahoma City",
    "El Paso",
    "Boston",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Kansas City",
    "Atlanta",
    "Miami",
    "Minneapolis",
    "New Orleans",
    "Arlington",
    "Tampa",
    "Honolulu",
    "Anaheim",
    "Aurora",
    "Corpus Christi",
    "Riverside",
    "St. Louis",
    "Lexington",
    "Pittsburgh",
    "Stockton",
    "Anchorage",
  ],
  GB: [
    "London",
    "Birmingham",
    "Manchester",
    "Leeds",
    "Sheffield",
    "Bradford",
    "Liverpool",
    "Bristol",
    "Leicester",
    "Edinburgh",
    "Glasgow",
    "Cardiff",
    "Belfast",
    "Nottingham",
    "Newcastle",
    "Southampton",
    "Portsmouth",
    "Brighton",
    "Reading",
    "Oxford",
    "Cambridge",
    "Coventry",
    "Wolverhampton",
    "Derby",
    "Stoke-on-Trent",
    "Plymouth",
    "Exeter",
    "Norwich",
    "York",
    "Bath",
    "Aberdeen",
    "Dundee",
    "Inverness",
    "Swansea",
    "Newport",
  ],
  AE: [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Ajman",
    "Ras Al Khaimah",
    "Fujairah",
    "Al Ain",
    "Umm Al Quwain",
    "Khor Fakkan",
    "Kalba",
  ],
  SA: [
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
    "Dammam",
    "Al Khobar",
    "Taif",
    "Abha",
    "Yanbu",
    "Tabuk",
    "Buraidah",
    "Khamis Mushait",
    "Al Hufuf",
    "Ha'il",
    "Najran",
    "Jizan",
    "Al Jubail",
    "Al Qatif",
    "Sakaka",
    "Arar",
    "Rafha",
    "Wadi ad-Dawasir",
  ],
  CA: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "Kitchener",
    "London",
    "Victoria",
    "Halifax",
    "Oshawa",
    "Windsor",
    "Saskatoon",
    "Regina",
    "Kelowna",
    "Barrie",
    "Sherbrooke",
    "Guelph",
    "Burnaby",
    "Abbotsford",
    "Sudbury",
    "Kingston",
    "Mississauga",
    "Brampton",
    "Markham",
    "Laval",
    "Surrey",
  ],
  AU: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Canberra",
    "Newcastle",
    "Wollongong",
    "Hobart",
    "Geelong",
    "Townsville",
    "Cairns",
    "Darwin",
    "Toowoomba",
    "Ballarat",
    "Bendigo",
    "Launceston",
    "Mackay",
    "Rockhampton",
  ],
  NZ: [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Dunedin",
    "Palmerston North",
    "Napier-Hastings",
    "Whangarei",
    "New Plymouth",
    "Rotorua",
    "Whanganui",
    "Nelson",
    "Invercargill",
    "Upper Hutt",
    "Lower Hutt",
    "Porirua",
    "Gisborne",
    "Blenheim",
    "Timaru",
  ],
  DE: [
    "Berlin",
    "Munich",
    "Frankfurt",
    "Hamburg",
    "Cologne",
    "Stuttgart",
    "Dusseldorf",
    "Leipzig",
    "Dortmund",
    "Bremen",
    "Hanover",
    "Nuremberg",
    "Dresden",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Mannheim",
    "Karlsruhe",
    "Augsburg",
    "Wiesbaden",
    "Munster",
    "Gelsenkirchen",
    "Aachen",
    "Braunschweig",
  ],
  HK: [
    "Hong Kong",
    "Kowloon",
    "Shatin",
    "Tsuen Wan",
    "Tsim Sha Tsui",
    "Mong Kok",
    "Yau Ma Tei",
    "Tuen Mun",
    "Yuen Long",
    "Tai Po",
    "Sai Kung",
    "Fanling",
    "Tseung Kwan O",
    "Kwun Tong",
    "Wong Tai Sin",
  ],
  MY: [
    "Kuala Lumpur",
    "George Town",
    "Johor Bahru",
    "Subang Jaya",
    "Shah Alam",
    "Ipoh",
    "Kuching",
    "Kota Kinabalu",
    "Petaling Jaya",
    "Klang",
    "Ampang Jaya",
    "Kuala Terengganu",
    "Kota Bharu",
    "Alor Setar",
    "Seremban",
    "Malacca City",
    "Miri",
    "Sandakan",
    "Tawau",
    "Bintulu",
  ],
  SG: [
    "Singapore",
    "Jurong",
    "Bedok",
    "Tampines",
    "Woodlands",
    "Sengkang",
    "Ang Mo Kio",
    "Punggol",
    "Hougang",
    "Bukit Merah",
    "Queenstown",
    "Bishan",
    "Toa Payoh",
    "Yishun",
    "Clementi",
  ],
  QA: [
    "Doha",
    "Al Rayyan",
    "Al Wakrah",
    "Al Khor",
    "Mesaieed",
    "Dukhan",
    "Umm Salal",
    "Al Shahaniya",
    "Madinat ash Shamal",
    "Al Wukair",
  ],
  ZA: [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
    "East London",
    "Richards Bay",
    "Polokwane",
    "Nelspruit",
    "Kimberley",
    "Rustenburg",
    "Pietermaritzburg",
    "Vereeniging",
    "Soweto",
    "Tembisa",
    "Witbank",
    "Vanderbijlpark",
    "George",
    "Middelburg",
  ],
  BD: [
    "Dhaka",
    "Chittagong",
    "Sylhet",
    "Rajshahi",
    "Khulna",
    "Barisal",
    "Rangpur",
    "Narayanganj",
    "Gazipur",
    "Bogra",
    "Comilla",
    "Mymensingh",
    "Jessore",
    "Dinajpur",
    "Sirajganj",
    "Tangail",
    "Pabna",
    "Brahmanbaria",
    "Noakhali",
    "Cox's Bazar",
  ],
  NG: [
    "Lagos",
    "Abuja",
    "Port Harcourt",
    "Kano",
    "Ibadan",
    "Kaduna",
    "Enugu",
    "Benin City",
    "Owerri",
    "Zaria",
    "Jos",
    "Maiduguri",
    "Warri",
    "Abeokuta",
    "Onitsha",
    "Ilorin",
    "Uyo",
    "Sokoto",
    "Bauchi",
    "Calabar",
    "Aba",
    "Makurdi",
    "Asaba",
    "Gombe",
    "Akure",
  ],
  EG: [
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El Kheima",
    "Port Said",
    "Mansoura",
    "Tanta",
    "Zagazig",
    "Luxor",
    "Aswan",
    "Ismailia",
    "Suez",
    "Asyut",
    "Damanhur",
    "Minya",
    "Sohag",
    "Qena",
    "Beni Suef",
    "El Obour",
    "New Cairo",
    "Hurghada",
    "Sharm el-Sheikh",
  ],
  PH: [
    "Manila",
    "Quezon City",
    "Cebu City",
    "Davao City",
    "Zamboanga City",
    "Baguio",
    "Iloilo City",
    "Cagayan de Oro",
    "Pasig",
    "Antipolo",
    "Makati",
    "Taguig",
    "Caloocan",
    "Las Pinas",
    "Muntinlupa",
    "Bacoor",
    "Parañaque",
    "Bacolod",
    "General Santos",
    "Lapu-Lapu City",
    "Tarlac City",
    "San Jose del Monte",
    "Butuan",
    "Cotabato City",
  ],
  ID: [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Medan",
    "Semarang",
    "Tangerang",
    "Yogyakarta",
    "Palembang",
    "Makassar",
    "Denpasar",
    "Bogor",
    "Depok",
    "Bekasi",
    "Malang",
    "Pekanbaru",
    "Bandar Lampung",
    "Padang",
    "Manado",
    "Samarinda",
    "Batam",
    "Balikpapan",
    "Pontianak",
    "Banjarmasin",
    "Jambi",
    "Jayapura",
  ],
  TR: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Bursa",
    "Adana",
    "Gaziantep",
    "Konya",
    "Antalya",
    "Kayseri",
    "Eskisehir",
    "Mersin",
    "Diyarbakir",
    "Samsun",
    "Urfa",
    "Malatya",
    "Denizli",
    "Kahramanmaras",
    "Trabzon",
    "Erzurum",
    "Van",
    "Manisa",
    "Balikesir",
    "Kocaeli",
    "Ordu",
    "Hatay",
  ],
  KW: [
    "Kuwait City",
    "Hawalli",
    "Salmiya",
    "Al Ahmadi",
    "Jahra",
    "Farwaniya",
    "Shuwaikh",
    "Mangaf",
    "Fintas",
    "Rumaithiya",
    "Salwa",
    "Mishref",
    "Sabah Al Salem",
    "Abu Halifa",
  ],
  OM: [
    "Muscat",
    "Salalah",
    "Sohar",
    "Barka",
    "Nizwa",
    "Sur",
    "Ibra",
    "Al Buraimi",
    "Rustaq",
    "Khasab",
    "Ibri",
    "Samail",
    "Al Suwaiq",
    "Bahla",
    "Adam",
  ],
  BH: [
    "Manama",
    "Muharraq",
    "Riffa",
    "Isa Town",
    "Hamad Town",
    "Sitra",
    "Juffair",
    "Adliya",
    "Amwaj Islands",
    "Seef",
    "Budaiya",
    "Tubli",
  ],
  IE: [
    "Dublin",
    "Cork",
    "Galway",
    "Limerick",
    "Waterford",
    "Kilkenny",
    "Sligo",
    "Drogheda",
    "Dundalk",
    "Bray",
    "Navan",
    "Ennis",
    "Tralee",
    "Carlow",
    "Newbridge",
    "Naas",
    "Clonmel",
    "Wexford",
    "Letterkenny",
    "Mullingar",
  ],
  FR: [
    "Paris",
    "Lyon",
    "Marseille",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Toulon",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nimes",
    "Villeurbanne",
    "Saint-Etienne",
    "Aix-en-Provence",
    "Clermont-Ferrand",
    "Tours",
    "Amiens",
    "Limoges",
    "Brest",
  ],
  NL: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Tilburg",
    "Groningen",
    "Almere",
    "Breda",
    "Nijmegen",
    "Apeldoorn",
    "Haarlem",
    "Enschede",
    "Arnhem",
    "Zaanstad",
    "Amersfoort",
    "Maastricht",
    "Dordrecht",
    "Leiden",
    "Haarlemmermeer",
  ],
  IT: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palermo",
    "Florence",
    "Bologna",
    "Venice",
    "Verona",
    "Genoa",
    "Catania",
    "Bari",
    "Messina",
    "Padua",
    "Trieste",
    "Brescia",
    "Taranto",
    "Prato",
    "Reggio Calabria",
    "Modena",
    "Parma",
    "Livorno",
    "Cagliari",
    "Foggia",
    "Perugia",
  ],
  ES: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Malaga",
    "Bilbao",
    "Murcia",
    "Alicante",
    "Las Palmas",
    "Cordoba",
    "Valladolid",
    "Vigo",
    "Gijon",
    "Granada",
    "Vitoria-Gasteiz",
    "Elche",
    "La Palmas de Gran Canaria",
    "Oviedo",
    "Badalona",
    "Cartagena",
    "Sabadell",
    "Terrassa",
    "Jerez de la Frontera",
    "Santa Cruz de Tenerife",
  ],
  JP: [
    "Tokyo",
    "Osaka",
    "Yokohama",
    "Nagoya",
    "Sapporo",
    "Kobe",
    "Kyoto",
    "Fukuoka",
    "Hiroshima",
    "Sendai",
    "Chiba",
    "Kitakyushu",
    "Sakai",
    "Kawasaki",
    "Okayama",
    "Kumamoto",
    "Shizuoka",
    "Hamamatsu",
    "Sagamihara",
    "Niigata",
    "Utsunomiya",
    "Matsuyama",
    "Matsumoto",
    "Naha",
    "Kanazawa",
  ],
  KR: [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Ulsan",
    "Suwon",
    "Sejong",
    "Goyang",
    "Yongin",
    "Changwon",
    "Seongnam",
    "Bucheon",
    "Ansan",
    "Jeonju",
    "Cheongju",
    "Anyang",
    "Pohang",
    "Uijeongbu",
  ],
  CN: [
    "Shanghai",
    "Beijing",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Chongqing",
    "Wuhan",
    "Xi'an",
    "Hangzhou",
    "Tianjin",
    "Nanjing",
    "Suzhou",
    "Dongguan",
    "Zhengzhou",
    "Foshan",
    "Shenyang",
    "Harbin",
    "Qingdao",
    "Kunming",
    "Changsha",
    "Dalian",
    "Jinan",
    "Nanning",
    "Changchun",
    "Hefei",
  ],
  TH: [
    "Bangkok",
    "Chiang Mai",
    "Phuket",
    "Pattaya",
    "Khon Kaen",
    "Hat Yai",
    "Chiang Rai",
    "Surat Thani",
    "Nakhon Ratchasima",
    "Udon Thani",
    "Ubon Ratchathani",
    "Nakhon Si Thammarat",
    "Rayong",
    "Ayutthaya",
    "Nonthaburi",
    "Pathum Thani",
    "Samut Prakan",
    "Songkhla",
    "Phitsanulok",
    "Lampang",
  ],
  VN: [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Hai Phong",
    "Can Tho",
    "Nha Trang",
    "Hue",
    "Bien Hoa",
    "Vung Tau",
    "Quy Nhon",
    "Buon Ma Thuot",
    "Long Xuyen",
    "Thai Nguyen",
    "Nam Dinh",
    "Vinh",
    "My Tho",
    "Rach Gia",
    "Da Lat",
    "Pleiku",
    "Bac Lieu",
  ],
  LK: [
    "Colombo",
    "Kandy",
    "Galle",
    "Jaffna",
    "Negombo",
    "Kurunegala",
    "Matara",
    "Gampaha",
    "Anuradhapura",
    "Polonnaruwa",
    "Badulla",
    "Ratnapura",
    "Trincomalee",
    "Batticaloa",
    "Vavuniya",
    "Mannar",
    "Kalmunai",
    "Hambantota",
    "Nuwara Eliya",
    "Chilaw",
  ],
  NP: [
    "Kathmandu",
    "Pokhara",
    "Lalitpur",
    "Bhaktapur",
    "Biratnagar",
    "Birgunj",
    "Dharan",
    "Janakpur",
    "Bharatpur",
    "Butwal",
    "Hetauda",
    "Dhangadhi",
    "Itahari",
    "Nepalgunj",
    "Tulsipur",
    "Ghorahi",
    "Lahan",
    "Rajbiraj",
    "Siddharthanagar",
    "Damak",
  ],
  KE: [
    "Nairobi",
    "Mombasa",
    "Kisumu",
    "Nakuru",
    "Eldoret",
    "Thika",
    "Nyeri",
    "Garissa",
    "Malindi",
    "Machakos",
    "Meru",
    "Kitale",
    "Naivasha",
    "Kisii",
    "Kakamega",
    "Kilifi",
    "Nanyuki",
    "Embu",
    "Kericho",
    "Athi River",
  ],
  GH: [
    "Accra",
    "Kumasi",
    "Tamale",
    "Sekondi-Takoradi",
    "Cape Coast",
    "Tema",
    "Koforidua",
    "Sunyani",
    "Ho",
    "Wa",
    "Bolgatanga",
    "Obuasi",
    "Techiman",
    "Teshie",
    "Ashaiman",
    "Winneba",
    "Nkawkaw",
    "Berekum",
    "Kasoa",
    "Bawku",
  ],
  MA: [
    "Casablanca",
    "Rabat",
    "Marrakech",
    "Fez",
    "Tangier",
    "Agadir",
    "Meknes",
    "Oujda",
    "Kenitra",
    "Tetouan",
    "Safi",
    "El Jadida",
    "Beni Mellal",
    "Nador",
    "Mohammedia",
    "Settat",
    "Larache",
    "Khemisset",
    "Berrechid",
    "Taza",
  ],
  JO: [
    "Amman",
    "Irbid",
    "Zarqa",
    "Aqaba",
    "Salt",
    "Karak",
    "Maan",
    "Mafraq",
    "Jerash",
    "Ajloun",
    "Madaba",
    "Ramtha",
    "Russeifa",
    "Sahab",
    "Wadi Musa",
  ],
  LB: [
    "Beirut",
    "Tripoli",
    "Sidon",
    "Zahle",
    "Baalbek",
    "Tyre",
    "Jounieh",
    "Nabatieh",
    "Byblos",
    "Aley",
    "Batroun",
    "Halba",
    "Jbeil",
    "Marjayoun",
  ],
  IQ: [
    "Baghdad",
    "Basra",
    "Erbil",
    "Mosul",
    "Kirkuk",
    "Karbala",
    "Najaf",
    "Duhok",
    "Nasiriyah",
    "Amarah",
    "Hillah",
    "Ramadi",
    "Fallujah",
    "Sulaymaniyah",
    "Baqubah",
    "Tikrit",
    "Kut",
    "Samarra",
    "Diwaniyah",
    "Khanaqin",
  ],
  BN: [
    "Bandar Seri Begawan",
    "Kuala Belait",
    "Seria",
    "Tutong",
    "Jerudong",
    "Mumong",
    "Berakas",
    "Kilanas",
  ],
  CH: [
    "Zurich",
    "Geneva",
    "Basel",
    "Bern",
    "Lausanne",
    "Lucerne",
    "St. Gallen",
    "Lugano",
    "Winterthur",
    "Biel/Bienne",
    "Thun",
    "Köniz",
    "La Chaux-de-Fonds",
    "Schaffhausen",
    "Fribourg",
    "Chur",
    "Neuchâtel",
    "Sion",
    "Uster",
    "Emmen",
  ],
  SE: [
    "Stockholm",
    "Gothenburg",
    "Malmö",
    "Uppsala",
    "Linkoping",
    "Vasteras",
    "Orebro",
    "Helsingborg",
    "Norrkoping",
    "Jonkoping",
    "Lund",
    "Umea",
    "Gavle",
    "Borås",
    "Eskilstuna",
    "Södertälje",
    "Karlstad",
    "Halmstad",
    "Växjö",
    "Sundsvall",
  ],
  NO: [
    "Oslo",
    "Bergen",
    "Trondheim",
    "Stavanger",
    "Drammen",
    "Kristiansand",
    "Tromso",
    "Fredrikstad",
    "Sandnes",
    "Baerum",
    "Aalesund",
    "Porsgrunn",
    "Skien",
    "Kristiansund",
    "Arendal",
    "Haugesund",
    "Moss",
    "Halden",
    "Bodø",
    "Gjøvik",
  ],
  PL: [
    "Warsaw",
    "Krakow",
    "Wroclaw",
    "Gdansk",
    "Poznan",
    "Lodz",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Katowice",
    "Bialystok",
    "Gdynia",
    "Czestochowa",
    "Radom",
    "Sosnowiec",
    "Kielce",
    "Rzeszow",
    "Gliwice",
    "Zabrze",
    "Torun",
    "Bytom",
    "Bielsko-Biala",
    "Olsztyn",
    "Ruda Slaska",
    "Rybnik",
  ],
  PT: [
    "Lisbon",
    "Porto",
    "Braga",
    "Coimbra",
    "Amadora",
    "Setubal",
    "Faro",
    "Viseu",
    "Leiria",
    "Funchal",
    "Almada",
    "Aveiro",
    "Barreiro",
    "Guimaraes",
    "Loures",
    "Matosinhos",
    "Vila Nova de Gaia",
    "Odivelas",
    "Cascais",
    "Sintra",
  ],
  MX: [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "Ciudad Juarez",
    "Leon",
    "Cancun",
    "Toluca",
    "Hermosillo",
    "Merida",
    "San Luis Potosi",
    "Aguascalientes",
    "Queretaro",
    "Morelia",
    "Chihuahua",
    "Mexicali",
    "Acapulco",
    "Culiacan",
    "Torreon",
    "Saltillo",
    "Veracruz",
    "Naucalpan",
    "Zapopan",
    "Ecatepec",
  ],
  BR: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Curitiba",
    "Manaus",
    "Recife",
    "Goiânia",
    "Belem",
    "Porto Alegre",
    "Guarulhos",
    "Campinas",
    "São Luís",
    "São Gonçalo",
    "Maceió",
    "Natal",
    "Teresina",
    "Campo Grande",
    "Nova Iguaçu",
    "Joao Pessoa",
    "Santo Andre",
    "Osasco",
    "Sorocaba",
  ],
};
