/** ISO 3166-1 alpha-2 markets we feature, with country-wise top tutoring subjects. */

import { MARKET_CITIES_BY_COUNTRY_CODE } from "@/lib/market-locations";

export type MarketCountry = {
  code: string;
  name: string;
  cities: string[];
  subjects: string[];
};

/** Pakistan first, then 49 more high tutoring-demand countries (50 total). */
const TOP_COUNTRIES_BASE: MarketCountry[] = [
  {
    code: "PK",
    name: "Pakistan",
    cities: ["Karachi", "Lahore", "Islamabad"],
    subjects: [
      "Mathematics",
      "Physics",
      "Chemistry",
      "Biology",
      "English",
      "Urdu",
      "O Level Maths",
      "A Level Chemistry",
      "IELTS",
      "CSS Prep",
      "Quran Nazra",
      "Computer Science",
    ],
  },
  {
    code: "IN",
    name: "India",
    cities: ["Mumbai", "Delhi", "Bangalore"],
    subjects: [
      "Mathematics",
      "Physics",
      "Chemistry",
      "Biology",
      "English",
      "JEE Prep",
      "NEET Prep",
      "CBSE Maths",
      "Spoken English",
      "Computer Science",
      "Accounting",
      "IELTS",
    ],
  },
  {
    code: "US",
    name: "United States",
    cities: ["New York", "Los Angeles", "Houston"],
    subjects: [
      "Mathematics",
      "SAT Prep",
      "ACT Prep",
      "AP Calculus",
      "English",
      "Spanish",
      "Physics",
      "Chemistry",
      "Computer Science",
      "Algebra",
      "Biology",
      "Writing",
    ],
  },
  {
    code: "GB",
    name: "United Kingdom",
    cities: ["London", "Manchester", "Birmingham"],
    subjects: [
      "Mathematics",
      "English",
      "GCSE Maths",
      "A Level Physics",
      "A Level Chemistry",
      "Biology",
      "11 Plus",
      "IELTS",
      "French",
      "Spanish",
      "Computer Science",
      "Economics",
    ],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    cities: ["Dubai", "Abu Dhabi", "Sharjah"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "IELTS",
      "Arabic",
      "IB Maths",
      "SAT Prep",
      "Computer Science",
      "Biology",
      "Accounting",
      "Spoken English",
    ],
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    cities: ["Riyadh", "Jeddah", "Dammam"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Arabic",
      "Quran Nazra",
      "IELTS",
      "SAT Prep",
      "Computer Science",
      "Biology",
      "Spoken English",
      "Islamic Studies",
    ],
  },
  {
    code: "CA",
    name: "Canada",
    cities: ["Toronto", "Vancouver", "Calgary"],
    subjects: [
      "Mathematics",
      "English",
      "French",
      "Physics",
      "Chemistry",
      "Biology",
      "SAT Prep",
      "Computer Science",
      "Calculus",
      "Accounting",
      "IELTS",
      "Spanish",
    ],
  },
  {
    code: "AU",
    name: "Australia",
    cities: ["Sydney", "Melbourne", "Brisbane"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "ATAR Maths",
      "IELTS",
      "Computer Science",
      "French",
      "Japanese",
      "Accounting",
      "Economics",
    ],
  },
  {
    code: "NZ",
    name: "New Zealand",
    cities: ["Auckland", "Wellington", "Christchurch"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Science",
      "Computer Science",
      "Economics",
      "Accounting",
      "French",
      "History",
      "Geography",
    ],
  },
  {
    code: "DE",
    name: "Germany",
    cities: ["Berlin", "Munich", "Frankfurt"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "German",
      "Computer Science",
      "Economics",
      "History",
      "Geography",
      "French",
      "Science",
    ],
  },
  {
    code: "HK",
    name: "Hong Kong",
    cities: ["Hong Kong", "Kowloon"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Chinese",
      "Computer Science",
      "Economics",
      "Accounting",
      "Business",
      "History",
      "Geography",
    ],
  },
  {
    code: "MY",
    name: "Malaysia",
    cities: ["Kuala Lumpur", "Penang", "Johor Bahru"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Bahasa Melayu",
      "Additional Maths",
      "IELTS",
      "Computer Science",
      "Accounting",
      "Mandarin",
      "SPM Maths",
    ],
  },
  {
    code: "SG",
    name: "Singapore",
    cities: ["Singapore"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Additional Maths",
      "Chinese",
      "PSLE Maths",
      "Computer Science",
      "Economics",
      "Accounting",
      "IELTS",
    ],
  },
  {
    code: "QA",
    name: "Qatar",
    cities: ["Doha"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Arabic",
      "IELTS",
      "SAT Prep",
      "Computer Science",
      "Biology",
      "Accounting",
      "IB Maths",
      "Quran Nazra",
    ],
  },
  {
    code: "ZA",
    name: "South Africa",
    cities: ["Johannesburg", "Cape Town", "Durban"],
    subjects: [
      "Mathematics",
      "English",
      "Physical Science",
      "Life Sciences",
      "Afrikaans",
      "Accounting",
      "Computer Science",
      "IELTS",
      "Economics",
      "Spoken English",
      "Biology",
      "Physics",
    ],
  },
  {
    code: "BD",
    name: "Bangladesh",
    cities: ["Dhaka", "Chittagong", "Sylhet"],
    subjects: [
      "Mathematics",
      "Physics",
      "Chemistry",
      "Biology",
      "English",
      "Bangla",
      "SSC Maths",
      "HSC Physics",
      "IELTS",
      "Computer Science",
      "Accounting",
      "Spoken English",
    ],
  },
  {
    code: "NG",
    name: "Nigeria",
    cities: ["Lagos", "Abuja", "Port Harcourt"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "WAEC Maths",
      "JAMB Prep",
      "Further Mathematics",
      "Economics",
      "Accounting",
      "Computer Science",
      "IELTS",
    ],
  },
  {
    code: "EG",
    name: "Egypt",
    cities: ["Cairo", "Alexandria", "Giza"],
    subjects: [
      "Mathematics",
      "English",
      "Arabic",
      "Physics",
      "Chemistry",
      "Biology",
      "French",
      "Computer Science",
      "IELTS",
      "SAT Prep",
      "Accounting",
      "Statistics",
    ],
  },
  {
    code: "PH",
    name: "Philippines",
    cities: ["Manila", "Quezon City", "Cebu"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Filipino",
      "Accounting",
      "IELTS",
      "Computer Science",
      "Economics",
      "Statistics",
      "Spoken English",
    ],
  },
  {
    code: "ID",
    name: "Indonesia",
    cities: ["Jakarta", "Surabaya", "Bandung"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Bahasa Indonesia",
      "Computer Science",
      "Accounting",
      "Economics",
      "IELTS",
      "Statistics",
      "Science",
    ],
  },
  {
    code: "TR",
    name: "Turkey",
    cities: ["Istanbul", "Ankara", "Izmir"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Turkish",
      "German",
      "Computer Science",
      "IELTS",
      "SAT Prep",
      "Economics",
      "Statistics",
    ],
  },
  {
    code: "KW",
    name: "Kuwait",
    cities: ["Kuwait City", "Hawalli", "Salmiya"],
    subjects: [
      "Mathematics",
      "English",
      "Arabic",
      "Physics",
      "Chemistry",
      "IELTS",
      "SAT Prep",
      "Computer Science",
      "Biology",
      "Accounting",
      "IB Maths",
      "Quran Nazra",
    ],
  },
  {
    code: "OM",
    name: "Oman",
    cities: ["Muscat", "Salalah", "Sohar"],
    subjects: [
      "Mathematics",
      "English",
      "Arabic",
      "Physics",
      "Chemistry",
      "IELTS",
      "SAT Prep",
      "Computer Science",
      "Biology",
      "Accounting",
      "Economics",
      "Islamic Studies",
    ],
  },
  {
    code: "BH",
    name: "Bahrain",
    cities: ["Manama", "Muharraq", "Riffa"],
    subjects: [
      "Mathematics",
      "English",
      "Arabic",
      "Physics",
      "Chemistry",
      "IELTS",
      "SAT Prep",
      "Computer Science",
      "Biology",
      "Accounting",
      "IB Maths",
      "Economics",
    ],
  },
  {
    code: "IE",
    name: "Ireland",
    cities: ["Dublin", "Cork", "Galway"],
    subjects: [
      "Mathematics",
      "English",
      "Irish",
      "Physics",
      "Chemistry",
      "Biology",
      "Leaving Cert Maths",
      "Junior Cert Maths",
      "French",
      "Computer Science",
      "Economics",
      "Accounting",
    ],
  },
  {
    code: "FR",
    name: "France",
    cities: ["Paris", "Lyon", "Marseille"],
    subjects: [
      "Mathematics",
      "English",
      "French",
      "Physics",
      "Chemistry",
      "Biology",
      "Philosophy",
      "Spanish",
      "German",
      "Computer Science",
      "Economics",
      "History",
    ],
  },
  {
    code: "NL",
    name: "Netherlands",
    cities: ["Amsterdam", "Rotterdam", "The Hague"],
    subjects: [
      "Mathematics",
      "English",
      "Dutch",
      "Physics",
      "Chemistry",
      "Biology",
      "Economics",
      "Computer Science",
      "French",
      "German",
      "History",
      "Geography",
    ],
  },
  {
    code: "IT",
    name: "Italy",
    cities: ["Rome", "Milan", "Naples"],
    subjects: [
      "Mathematics",
      "English",
      "Italian",
      "Physics",
      "Chemistry",
      "Biology",
      "Latin",
      "French",
      "Computer Science",
      "Economics",
      "History",
      "Geography",
    ],
  },
  {
    code: "ES",
    name: "Spain",
    cities: ["Madrid", "Barcelona", "Valencia"],
    subjects: [
      "Mathematics",
      "English",
      "Spanish",
      "Physics",
      "Chemistry",
      "Biology",
      "French",
      "Computer Science",
      "Economics",
      "History",
      "Geography",
      "Catalan",
    ],
  },
  {
    code: "JP",
    name: "Japan",
    cities: ["Tokyo", "Osaka", "Yokohama"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Japanese",
      "Computer Science",
      "Economics",
      "History",
      "Geography",
      "Statistics",
      "Science",
    ],
  },
  {
    code: "KR",
    name: "South Korea",
    cities: ["Seoul", "Busan", "Incheon"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Korean",
      "Computer Science",
      "Economics",
      "History",
      "SAT Prep",
      "Statistics",
      "Science",
    ],
  },
  {
    code: "CN",
    name: "China",
    cities: ["Shanghai", "Beijing", "Guangzhou"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Chinese",
      "Mandarin",
      "Computer Science",
      "Economics",
      "IELTS",
      "Statistics",
      "History",
    ],
  },
  {
    code: "TH",
    name: "Thailand",
    cities: ["Bangkok", "Chiang Mai", "Phuket"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Thai",
      "Computer Science",
      "Accounting",
      "Economics",
      "IELTS",
      "Statistics",
      "Science",
    ],
  },
  {
    code: "VN",
    name: "Vietnam",
    cities: ["Ho Chi Minh City", "Hanoi", "Da Nang"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Vietnamese",
      "Computer Science",
      "Accounting",
      "Economics",
      "IELTS",
      "Statistics",
      "Science",
    ],
  },
  {
    code: "LK",
    name: "Sri Lanka",
    cities: ["Colombo", "Kandy", "Galle"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Sinhala",
      "Tamil",
      "Accounting",
      "Economics",
      "Computer Science",
      "IELTS",
      "Statistics",
    ],
  },
  {
    code: "NP",
    name: "Nepal",
    cities: ["Kathmandu", "Pokhara", "Lalitpur"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Nepali",
      "Accounting",
      "Economics",
      "Computer Science",
      "IELTS",
      "Statistics",
      "Science",
    ],
  },
  {
    code: "KE",
    name: "Kenya",
    cities: ["Nairobi", "Mombasa", "Kisumu"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Kiswahili",
      "Computer Science",
      "Accounting",
      "Economics",
      "History",
      "Geography",
      "Business Studies",
    ],
  },
  {
    code: "GH",
    name: "Ghana",
    cities: ["Accra", "Kumasi", "Tamale"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "WAEC Maths",
      "Computer Science",
      "Accounting",
      "Economics",
      "History",
      "Geography",
      "Integrated Science",
    ],
  },
  {
    code: "MA",
    name: "Morocco",
    cities: ["Casablanca", "Rabat", "Marrakech"],
    subjects: [
      "Mathematics",
      "English",
      "French",
      "Arabic",
      "Physics",
      "Chemistry",
      "Biology",
      "Computer Science",
      "Economics",
      "Accounting",
      "Statistics",
      "History",
    ],
  },
  {
    code: "JO",
    name: "Jordan",
    cities: ["Amman", "Irbid", "Zarqa"],
    subjects: [
      "Mathematics",
      "English",
      "Arabic",
      "Physics",
      "Chemistry",
      "Biology",
      "IELTS",
      "SAT Prep",
      "Computer Science",
      "Accounting",
      "Economics",
      "Islamic Studies",
    ],
  },
  {
    code: "LB",
    name: "Lebanon",
    cities: ["Beirut", "Tripoli", "Sidon"],
    subjects: [
      "Mathematics",
      "English",
      "Arabic",
      "French",
      "Physics",
      "Chemistry",
      "Biology",
      "IELTS",
      "SAT Prep",
      "Computer Science",
      "Economics",
      "History",
    ],
  },
  {
    code: "IQ",
    name: "Iraq",
    cities: ["Baghdad", "Basra", "Erbil"],
    subjects: [
      "Mathematics",
      "English",
      "Arabic",
      "Physics",
      "Chemistry",
      "Biology",
      "Computer Science",
      "Economics",
      "Accounting",
      "Statistics",
      "History",
      "Islamic Studies",
    ],
  },
  {
    code: "BN",
    name: "Brunei",
    cities: ["Bandar Seri Begawan"],
    subjects: [
      "Mathematics",
      "English",
      "Physics",
      "Chemistry",
      "Biology",
      "Malay",
      "Additional Maths",
      "Computer Science",
      "Accounting",
      "Economics",
      "IGCSE Maths",
      "IELTS",
    ],
  },
  {
    code: "CH",
    name: "Switzerland",
    cities: ["Zurich", "Geneva", "Basel"],
    subjects: [
      "Mathematics",
      "English",
      "German",
      "French",
      "Physics",
      "Chemistry",
      "Biology",
      "Economics",
      "Computer Science",
      "Italian",
      "History",
      "Geography",
    ],
  },
  {
    code: "SE",
    name: "Sweden",
    cities: ["Stockholm", "Gothenburg", "Malmö"],
    subjects: [
      "Mathematics",
      "English",
      "Swedish",
      "Physics",
      "Chemistry",
      "Biology",
      "Computer Science",
      "Economics",
      "History",
      "Geography",
      "French",
      "German",
    ],
  },
  {
    code: "NO",
    name: "Norway",
    cities: ["Oslo", "Bergen", "Trondheim"],
    subjects: [
      "Mathematics",
      "English",
      "Norwegian",
      "Physics",
      "Chemistry",
      "Biology",
      "Computer Science",
      "Economics",
      "History",
      "Geography",
      "French",
      "German",
    ],
  },
  {
    code: "PL",
    name: "Poland",
    cities: ["Warsaw", "Krakow", "Wroclaw"],
    subjects: [
      "Mathematics",
      "English",
      "Polish",
      "Physics",
      "Chemistry",
      "Biology",
      "Computer Science",
      "Economics",
      "History",
      "Geography",
      "German",
      "French",
    ],
  },
  {
    code: "PT",
    name: "Portugal",
    cities: ["Lisbon", "Porto", "Braga"],
    subjects: [
      "Mathematics",
      "English",
      "Portuguese",
      "Physics",
      "Chemistry",
      "Biology",
      "Computer Science",
      "Economics",
      "History",
      "Geography",
      "French",
      "Spanish",
    ],
  },
  {
    code: "MX",
    name: "Mexico",
    cities: ["Mexico City", "Guadalajara", "Monterrey"],
    subjects: [
      "Mathematics",
      "English",
      "Spanish",
      "Physics",
      "Chemistry",
      "Biology",
      "Calculus",
      "Computer Science",
      "Economics",
      "Accounting",
      "History",
      "Statistics",
    ],
  },
  {
    code: "BR",
    name: "Brazil",
    cities: ["São Paulo", "Rio de Janeiro", "Brasília"],
    subjects: [
      "Mathematics",
      "English",
      "Portuguese",
      "Physics",
      "Chemistry",
      "Biology",
      "Computer Science",
      "Economics",
      "Accounting",
      "Statistics",
      "History",
      "Geography",
    ],
  },
];

/**
 * Expand cities per country for search + profile filters.
 * Subjects remain defined in this file.
 */
export const TOP_COUNTRIES: MarketCountry[] = TOP_COUNTRIES_BASE.map((country) => ({
  ...country,
  cities: MARKET_CITIES_BY_COUNTRY_CODE[country.code] || country.cities,
}));

/** Top 8 countries shown as cards on the homepage. */
export const HOMEPAGE_FEATURED_COUNTRY_CODES = [
  "PK",
  "IN",
  "US",
  "GB",
  "AE",
  "SA",
  "CA",
  "AU",
] as const;

const HOMEPAGE_FEATURED = new Set<string>(HOMEPAGE_FEATURED_COUNTRY_CODES);

export function allMarketSubjects() {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const country of TOP_COUNTRIES) {
    for (const subject of country.subjects) {
      if (seen.has(subject)) continue;
      seen.add(subject);
      out.push(subject);
    }
  }
  return out;
}

export function allMarketCities() {
  const seen = new Set<string>();
  const out: string[] = ["Online"];
  for (const country of TOP_COUNTRIES) {
    for (const city of country.cities) {
      if (seen.has(city)) continue;
      seen.add(city);
      out.push(city);
    }
  }
  return out;
}

export function countryByCode(code: string) {
  return TOP_COUNTRIES.find((c) => c.code === code.toUpperCase()) || null;
}

export function countryByName(name: string) {
  return TOP_COUNTRIES.find((c) => c.name.toLowerCase() === name.toLowerCase()) || null;
}

export function homepageFeaturedCountries() {
  return HOMEPAGE_FEATURED_COUNTRY_CODES.map((code) => countryByCode(code)).filter(
    (c): c is MarketCountry => c !== null,
  );
}

export function otherMarketCountries() {
  return TOP_COUNTRIES.filter((c) => !HOMEPAGE_FEATURED.has(c.code));
}

export const FEATURED_COUNTRY_LIMIT = 8;

/**
 * Exactly 8 country cards, plus the remaining markets for a dropdown.
 * If the visitor's country is not already in the 8, it replaces the last slot.
 */
export function selectFeaturedMarketCountries(pinnedName?: string | null): {
  featured: MarketCountry[];
  rest: MarketCountry[];
} {
  const seen = new Set<string>();
  const featured: MarketCountry[] = [];
  for (const country of [...homepageFeaturedCountries(), ...TOP_COUNTRIES]) {
    if (seen.has(country.code)) continue;
    seen.add(country.code);
    featured.push(country);
    if (featured.length === FEATURED_COUNTRY_LIMIT) break;
  }

  const pinned = pinnedName
    ? featured.find((c) => c.name === pinnedName) || countryByName(pinnedName)
    : null;

  if (pinned) {
    if (featured.some((c) => c.code === pinned.code)) {
      featured.splice(0, featured.length, pinned, ...featured.filter((c) => c.code !== pinned.code));
    } else {
      featured.splice(0, featured.length, pinned, ...featured.slice(0, FEATURED_COUNTRY_LIMIT - 1));
    }
  }

  const featuredCodes = new Set(featured.map((c) => c.code));
  const rest = TOP_COUNTRIES.filter((c) => !featuredCodes.has(c.code)).sort((a, b) =>
    a.name.localeCompare(b.name),
  );

  return { featured: featured.slice(0, FEATURED_COUNTRY_LIMIT), rest };
}

/** Short subject codes shown on chips and the directory (not ISO country codes). */
export const SUBJECT_CODES: Record<string, string> = {
  Mathematics: "MATH",
  Physics: "PHY",
  Chemistry: "CHEM",
  Biology: "BIO",
  English: "ENG",
  Urdu: "URDU",
  "O Level Maths": "OLM",
  "A Level Physics": "ALP",
  "A Level Chemistry": "ALC",
  IELTS: "IELTS",
  "CSS Prep": "CSS",
  "Quran Nazra": "QRN",
  "Computer Science": "CS",
  "JEE Prep": "JEE",
  "NEET Prep": "NEET",
  "CBSE Maths": "CBSE",
  "Spoken English": "SPE",
  Accounting: "ACC",
  "SAT Prep": "SAT",
  "ACT Prep": "ACT",
  "AP Calculus": "APC",
  Spanish: "SPAN",
  Algebra: "ALG",
  Writing: "WRIT",
  "GCSE Maths": "GCSE",
  "11 Plus": "11P",
  French: "FR",
  Economics: "ECON",
  Arabic: "AR",
  "IB Maths": "IBM",
  "Islamic Studies": "ISL",
  Islamiyat: "ISLM",
  "Pakistan Studies": "PST",
  Calculus: "CALC",
  "ATAR Maths": "ATAR",
  Japanese: "JPN",
  Bangla: "BNG",
  "SSC Maths": "SSC",
  "HSC Physics": "HSC",
  "IGCSE Maths": "IGCSE",
  "WAEC Maths": "WAEC",
  "JAMB Prep": "JAMB",
  "Bahasa Melayu": "BM",
  "Additional Maths": "ADD",
  Mandarin: "MAN",
  "SPM Maths": "SPM",
  Chinese: "CHI",
  "PSLE Maths": "PSLE",
  "Physical Science": "PSCI",
  "Life Sciences": "LIFE",
  Afrikaans: "AFR",
  "Primary School": "PRI",
  "Music Piano": "PIANO",
  Guitar: "GTR",
  Business: "BUS",
  Science: "SCI",
  Psychology: "PSY",
  Geography: "GEO",
  History: "HIST",
  "Social Studies": "SS",
  Statistics: "STAT",
  German: "GER",
  Computing: "COMP",
  Commerce: "COMM",
  "English Language Arts": "ELA",
  Humanities: "HUM",
  "Additional Mathematics": "ADD",
  "Business Studies": "BST",
  Technology: "TECH",
  "Physical Sciences": "PSCI",
  "General Studies": "GS",
  "Computer Applications": "CA",
  Health: "HLTH",
  "Further Mathematics": "FMTH",
  "Natural Sciences": "NSCI",
  Reading: "READ",
  "Calculus AB": "CAB",
  "Calculus BC": "CBC",
  "Reading and Writing": "RW",
  Filipino: "FIL",
  "Bahasa Indonesia": "IND",
  Turkish: "TUR",
  Irish: "IR",
  Philosophy: "PHIL",
  Dutch: "DUT",
  Italian: "ITA",
  Latin: "LAT",
  Catalan: "CAT",
  Korean: "KOR",
  Thai: "THA",
  Vietnamese: "VIE",
  Sinhala: "SIN",
  Tamil: "TAM",
  Nepali: "NEP",
  Kiswahili: "SWA",
  "Integrated Science": "ISCI",
  Malay: "MAL",
  Swedish: "SWE",
  Norwegian: "NOR",
  Polish: "POL",
  Portuguese: "POR",
  "Leaving Cert Maths": "LCM",
  "Junior Cert Maths": "JCM",
};

export function subjectCode(name: string) {
  if (SUBJECT_CODES[name]) return SUBJECT_CODES[name];
  const parts = name.replace(/[^A-Za-z0-9 ]/g, "").split(/\s+/).filter(Boolean);
  if (parts.length === 1) return parts[0].slice(0, 4).toUpperCase();
  return parts
    .map((p) => p[0])
    .join("")
    .slice(0, 4)
    .toUpperCase();
}
