/**
 * Centralized city lists for each featured country.
 *
 * These power:
 * - search country + city filters
 * - tutor profile country + city dropdowns
 * - city inference for free-text searches
 *
 * Important: Do not include "Online" here. "Online" is added by the callers.
 */
export const MARKET_CITIES_BY_COUNTRY_CODE: Record<string, string[]> = {
  // South Asia + MENA (kept in the same order as `TOP_COUNTRIES` for predictable sorting).
  PK: [
    "Karachi",
    "Lahore",
    "Islamabad",
    "Rawalpindi",
    "Faisalabad",
    "Peshawar",
    "Multan",
    "Quetta",
    "Hyderabad",
    "Sialkot",
    "Gujranwala",
    "Abbottabad",
    "Bahawalpur",
  ],
  IN: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Ahmedabad",
    "Pune",
    "Jaipur",
    "Lucknow",
    "Chandigarh",
    "Nagpur",
  ],
  US: [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
  ],
  GB: [
    "London",
    "Manchester",
    "Birmingham",
    "Leeds",
    "Glasgow",
    "Edinburgh",
    "Liverpool",
    "Bristol",
    "Nottingham",
    "Sheffield",
    "Cardiff",
    "Leicester",
  ],
  AE: [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Ajman",
    "Al Ain",
    "Ras Al Khaimah",
    "Fujairah",
    "Umm al-Quwain",
  ],
  SA: [
    "Riyadh",
    "Jeddah",
    "Dammam",
    "Al Khobar",
    "Medina",
    "Mecca",
    "Taif",
    "Abha",
    "Yanbu",
  ],
  CA: [
    "Toronto",
    "Vancouver",
    "Calgary",
    "Montreal",
    "Ottawa",
    "Edmonton",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "Mississauga",
  ],
  AU: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Canberra",
    "Gold Coast",
    "Hobart",
    "Geelong",
  ],
  NZ: [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Dunedin",
    "Palmerston North",
    "Napier-Hastings",
    "Whangarei",
  ],
  DE: [
    "Berlin",
    "Munich",
    "Frankfurt",
    "Hamburg",
    "Cologne",
    "Stuttgart",
    "Dusseldorf",
    "Leipzig",
    "Dortmund",
    "Bremen",
    "Hanover",
  ],
  HK: ["Hong Kong", "Kowloon", "Shatin", "Tsuen Wan", "Tsim Sha Tsui", "Mong Kok", "Yau Ma Tei"],
  MY: [
    "Kuala Lumpur",
    "George Town",
    "Johor Bahru",
    "Subang Jaya",
    "Shah Alam",
    "Ipoh",
    "Kuching",
    "Kota Kinabalu",
  ],
  SG: ["Singapore", "Jurong", "Bedok", "Tampines", "Woodlands", "Sengkang", "Ang Mo Kio", "Punggol"],
  QA: ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Mesaieed", "Dukhan", "Umm Salal"],
  ZA: [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
    "East London",
    "Richards Bay",
    "Polokwane",
  ],
  BD: [
    "Dhaka",
    "Chittagong",
    "Sylhet",
    "Rajshahi",
    "Khulna",
    "Barisal",
    "Rangpur",
    "Narayanganj",
    "Gazipur",
    "Bogra",
  ],
  NG: [
    "Lagos",
    "Abuja",
    "Port Harcourt",
    "Kano",
    "Ibadan",
    "Kaduna",
    "Enugu",
    "Benin City",
    "Owerri",
    "Zaria",
  ],
  EG: [
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El Kheima",
    "Port Said",
    "Mansoura",
    "Tanta",
    "Zagazig",
    "Luxor",
    "Aswan",
  ],
  PH: [
    "Manila",
    "Quezon City",
    "Cebu City",
    "Davao City",
    "Zamboanga City",
    "Baguio",
    "Iloilo City",
    "Cagayan de Oro",
    "Pasig",
    "Antipolo",
  ],
  ID: [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Medan",
    "Semarang",
    "Tangerang",
    "Yogyakarta",
    "Palembang",
    "Makassar",
    "Denpasar",
  ],
  TR: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Bursa",
    "Adana",
    "Gaziantep",
    "Konya",
    "Antalya",
    "Kayseri",
    "Eskisehir",
  ],
  KW: ["Kuwait City", "Hawalli", "Salmiya", "Al Ahmadi", "Jahra", "Farwaniya", "Shuwaikh", "Mangaf"],
  OM: ["Muscat", "Salalah", "Sohar", "Barka", "Nizwa", "Sur", "Ibra", "Al Buraimi"],
  BH: ["Manama", "Muharraq", "Riffa", "Isa Town", "Hamad Town", "Sitra", "Juffair"],
  IE: ["Dublin", "Cork", "Galway", "Limerick", "Waterford", "Kilkenny", "Sligo", "Drogheda"],
  FR: [
    "Paris",
    "Lyon",
    "Marseille",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
  ],
  NL: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda"],
  IT: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palermo",
    "Florence",
    "Bologna",
    "Venice",
    "Verona",
    "Genoa",
  ],
  ES: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Malaga",
    "Bilbao",
    "Murcia",
    "Alicante",
    "Las Palmas",
  ],
  JP: [
    "Tokyo",
    "Osaka",
    "Yokohama",
    "Nagoya",
    "Sapporo",
    "Kobe",
    "Kyoto",
    "Fukuoka",
    "Hiroshima",
    "Sendai",
  ],
  KR: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Ulsan", "Suwon", "Sejong"],
  CN: [
    "Shanghai",
    "Beijing",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Chongqing",
    "Wuhan",
    "Xi'an",
    "Hangzhou",
    "Tianjin",
  ],
  TH: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Khon Kaen", "Hat Yai", "Chiang Rai", "Surat Thani"],
  VN: [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Hai Phong",
    "Can Tho",
    "Nha Trang",
    "Hue",
    "Bien Hoa",
    "Vung Tau",
    "Quy Nhon",
  ],
  LK: ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo", "Kurunegala", "Matara", "Gampaha"],
  NP: ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Biratnagar", "Birgunj", "Dharan", "Janakpur"],
  KE: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Nyeri", "Garissa"],
  GH: ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Cape Coast", "Tema", "Koforidua", "Sunyani"],
  MA: ["Casablanca", "Rabat", "Marrakech", "Fez", "Tangier", "Agadir", "Meknes", "Oujda"],
  JO: ["Amman", "Irbid", "Zarqa", "Aqaba", "Salt", "Karak", "Maan"],
  LB: ["Beirut", "Tripoli", "Sidon", "Zahle", "Baalbek", "Tyre", "Jounieh"],
  IQ: ["Baghdad", "Basra", "Erbil", "Mosul", "Kirkuk", "Karbala", "Najaf", "Duhok"],
  BN: ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Jerudong"],
  CH: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Lucerne", "St. Gallen", "Lugano"],
  SE: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Linkoping", "Vasteras", "Orebro", "Helsingborg"],
  NO: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Kristiansand", "Tromso", "Fredrikstad"],
  PL: [
    "Warsaw",
    "Krakow",
    "Wroclaw",
    "Gdansk",
    "Poznan",
    "Lodz",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Katowice",
  ],
  PT: ["Lisbon", "Porto", "Braga", "Coimbra", "Amadora", "Setubal", "Faro", "Viseu", "Leiria"],
  MX: [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "Ciudad Juarez",
    "Leon",
    "Cancun",
    "Toluca",
    "Hermosillo",
  ],
  BR: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Curitiba",
    "Manaus",
    "Recife",
    "Goiânia",
  ],
};

